export default [
    {
        id: 1,
        shopTicker: "hm",
        shopName: "H&M",
        shopIcon: "hm_white",
        type: "discout",
        amount: 10,
        cost: 1000,
        description: "10% discount on your next purchase",
        color: "red",
    },
    {
        id: 1,
        shopTicker: "reserved",
        shopName: "Reserved",
        shopIcon: "reserved",
        type: "discout",
        amount: 15,
        cost: 1500,
        description: "10% discount on your next purchase",
        color: "lightgrey",
    },
    {
        id: 1,
        shopTicker: "diverse",
        shopName: "Diverse",
        shopIcon: "diverse",
        type: "discout",
        amount: 10,
        cost: 1500,
        description: "10% discount on your next purchase",
        color: "#fff",
    },
    {
        id: 1,
        shopTicker: "vistula",
        shopName: "Vistula",
        shopIcon: "vistula",
        type: "discount",
        amount: 15,
        cost: 700,
        description: "10% discount on your next purchase",
        color: "lightgreen",
    },
    {
        id: 1,
        shopTicker: "zara",
        shopName: "Zara",
        shopIcon: "zara",
        type: "discout",
        amount: 25,
        cost: 900,
        description: "10% discount on your next purchase",
        color: "orange",
    },
    {
        id: 1,
        shopTicker: "4f",
        shopName: "4F",
        shopIcon: "4f",
        type: "discout",
        amount: 15,
        cost: 1200,
        description: "10% discount on your next purchase",
        color: "lightblue",
    },
];